import Atlas.LinearGroups.G2.PairStabilizer
import Atlas.LinearGroups.G2.VectorStabilizer
import Atlas.LinearGroups.G2.Torus

/-!
# The displayed roots, Weyl maps, and torus generate the full automorphism group

The root E and its conjugate by H(-1,1)r supply the two SL2 transvection
families in the full opposite-vector stabilizer. The verified SL2 elementary
generation theorem therefore puts that stabilizer inside the displayed group.
The partner-coordinate normalization gives the whole first-vector stabilizer.
Finally singular-vector reduction followed by a torus scaling reduces every
actual automorphism to that stabilizer. No group-order comparison is used.
-/
noncomputable section

namespace Atlas.G2
open Atlas.SplitOctonion Explicit Matrix PairStabilizer
open scoped MatrixGroups
variable {F : Type*} [Field F]

/-- The subgroup generated by the explicit six root families, Weyl maps, and torus. -/
def generated : Subgroup (Model F) := rootWeylSubgroup ⊔ splitTorus

theorem rootWeyl_le_generated : rootWeylSubgroup (K := F) ≤ generated := le_sup_left
theorem torus_mem_generated (l m : Fˣ) : torus l m ∈ generated :=
  (show splitTorus ≤ generated (F := F) from le_sup_right)
    (show torus l m ∈ splitTorus from ⟨(l,m),rfl⟩)

theorem rootE_mem_generated (a : F) : rootE a ∈ generated := by
  apply rootWeyl_le_generated
  apply Subgroup.subset_closure
  exact Or.inl (Subgroup.subset_closure (by simp))

def upperSL (a : F) : SL(2,F) :=
  Matrix.SpecialLinearGroup.transvection (by decide : (0 : Fin 2) ≠ 1) a

def lowerSL (a : F) : SL(2,F) :=
  Matrix.SpecialLinearGroup.transvection (by decide : (1 : Fin 2) ≠ 0) a

def rankOneJ : SL(2,F) := ⟨!![0,1;-1,0],by simp⟩

theorem block_upper (a : F) : blockHom (upperSL a) = rootE a := by
  apply Subtype.ext
  apply LinearEquiv.ext
  intro x
  funext i
  fin_cases i <;> simp [blockHom,blockEquiv,blockLinear,upperSL,
    Matrix.SpecialLinearGroup.transvection,Matrix.transvection,rootE,rootEEquiv,
    rootELinear,rootEApply]

theorem block_rankOneJ : blockHom (rankOneJ (F := F)) = torus (-1) 1 * weylR := by
  apply Subtype.ext
  apply LinearEquiv.ext
  intro x
  funext i
  fin_cases i <;> simp [blockHom,blockEquiv,blockLinear,rankOneJ,
    torus,torusEquiv,torusLinear,torusWeights,weylR,weylREquiv,weylRLinear,weylRApply]

theorem lowerSL_conjugate (a : F) : lowerSL a = rankOneJ * upperSL (-a) * rankOneJ⁻¹ := by
  apply Subtype.ext
  change Matrix.transvection 1 0 a =
    !![0,1;-1,0] * Matrix.transvection 0 1 (-a) * Matrix.adjugate !![0,1;-1,0]
  funext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.transvection,Matrix.adjugate_fin_two,Matrix.mul_apply,Matrix.vecMul,dotProduct,Fin.sum_univ_two]

theorem block_mem_generated (M : SL(2,F)) : blockHom M ∈ generated := by
  have hJ : blockHom (rankOneJ (F := F)) ∈ generated := by
    rw [block_rankOneJ]
    apply generated.mul_mem (torus_mem_generated _ _)
    exact rootWeyl_le_generated (Subgroup.subset_closure (by simp))
  apply Matrix.SL2.transvection_induction (fun M => blockHom M ∈ generated) ?_ ?_ M
  · intro i j hij a
    fin_cases i <;> fin_cases j
    · exact (hij rfl).elim
    · change blockHom (upperSL a) ∈ generated
      rw [block_upper]
      exact rootE_mem_generated a
    · change blockHom (lowerSL a) ∈ generated
      rw [lowerSL_conjugate,map_mul,map_mul,map_inv,block_upper]
      exact generated.mul_mem (generated.mul_mem hJ (rootE_mem_generated _))
        (generated.inv_mem hJ)
    · exact (hij rfl).elim
  · intro A B hA hB
    rw [map_mul]
    exact generated.mul_mem hA hB

theorem fixingPair_le_generated : fixingPair (F := F) ≤ generated := by
  intro g hg
  let p : fixingPair (F := F) := ⟨g,hg⟩
  have he := congrArg Subtype.val (block_imageSL p)
  change blockHom (imageSL p) = g at he
  rw [← he]
  exact block_mem_generated _

theorem fixingFirstVector_le_generated : fixingFirstVector (K := F) ≤ generated := by
  intro g hg
  let p : fixingFirstVector (K := F) := ⟨g,hg⟩
  have hn := fixingPair_le_generated (normalizedPair p).prop
  have hs := rootWeyl_le_generated (chartReducer_mem (partnerOf p).val)
  have h := generated.mul_mem (generated.inv_mem hs) hn
  change (chartReducer (partnerOf p).val)⁻¹ *
    ((chartReducer (partnerOf p).val) * g) ∈ generated at h
  simpa only [inv_mul_cancel_left] using h

/-- Coordinate reduction and the full vector stabilizer generate every actual automorphism. -/
theorem generated_eq_top : generated (F := F) = ⊤ := by
  apply top_unique
  intro g _
  have ht : trace (g.val (basisVector 0)) = 0 := by
    rw [automorphism_trace]
    simp [trace,basisVector]
  have hn : SplitOctonion.norm (g.val (basisVector 0)) = 0 := by
    rw [automorphism_norm]
    simp [SplitOctonion.norm,basisVector]
  have hx : g.val (basisVector 0) ≠ 0 := by
    intro h
    have hh := g.val.injective (h.trans (map_zero g.val).symm)
    have hi := congrFun hh 0
    simp [basisVector] at hi
  obtain ⟨w,hw,r,hr,he⟩ := singular_vector_reduction_first (g.val (basisVector 0)) ht hn hx
  let t : Model F := torus (Units.mk0 r hr)⁻¹ 1
  have htmem : t ∈ generated := torus_mem_generated _ _
  have htfix : t.val (r • basisVector 0) = basisVector 0 := by
    funext i
    fin_cases i <;> simp [t,torus,torusEquiv,torusLinear,torusWeights,basisVector,hr]
  have hfix : t*w*g ∈ fixingFirstVector := by
    change t.val (w.val (g.val (basisVector 0))) = basisVector 0
    rw [he,htfix]
  have hmem := fixingFirstVector_le_generated hfix
  have hwmem := rootWeyl_le_generated hw
  have h := generated.mul_mem (generated.inv_mem (generated.mul_mem htmem hwmem)) hmem
  simpa only [inv_mul_cancel_left] using h

end Atlas.G2
