import Atlas.LinearGroups.G2.Generation
import Atlas.LinearGroups.G2.PointStabilizer
import Atlas.LinearGroups.G2.Borel
import Atlas.LinearGroups.SL2Order

noncomputable section
namespace Atlas.G2
open Atlas.SplitOctonion Explicit Matrix PairStabilizer
open scoped MatrixGroups
variable {F : Type*} [Field F]

/-- The explicit rank-one parabolic generated by Borel and the long Weyl involution. -/
def parabolic : Subgroup (Model F) := borel ⊔ Subgroup.closure {weylR}

theorem unipotent_le_parabolic : unipotent (K := F) ≤ parabolic :=
  le_trans le_sup_left le_sup_left

theorem torus_mem_parabolic (l m : Fˣ) : torus l m ∈ parabolic :=
  (show splitTorus ≤ parabolic (F := F) from le_trans le_sup_right le_sup_left)
    (show torus l m ∈ splitTorus from ⟨(l,m),rfl⟩)

theorem weylR_mem_parabolic : (weylR : Model F) ∈ parabolic :=
  Subgroup.mem_sup_right (Subgroup.subset_closure (by simp))

theorem rootE_mem_parabolic (a : F) : rootE a ∈ parabolic :=
  unipotent_le_parabolic (Subgroup.subset_closure (by simp [unipotent]))

theorem chartReducer_mem_unipotent (x : Carrier F) : chartReducer x ∈ unipotent := by
  have hA : ∀ a : F, rootA a ∈ unipotent := fun a => Subgroup.subset_closure (by simp [unipotent])
  have hB : ∀ a : F, rootB a ∈ unipotent := fun a => Subgroup.subset_closure (by simp [unipotent])
  have hC : ∀ a : F, rootC a ∈ unipotent := fun a => Subgroup.subset_closure (by simp [unipotent])
  have hD : ∀ a : F, rootD a ∈ unipotent := fun a => Subgroup.subset_closure (by simp [unipotent])
  have hF : ∀ a : F, rootF a ∈ unipotent := fun a => Subgroup.subset_closure (by simp [unipotent])
  exact unipotent.mul_mem (unipotent.mul_mem (unipotent.mul_mem
    (unipotent.mul_mem (hB _) (hA _)) (hC _)) (hD _)) (hF _)

theorem block_mem_parabolic (M : SL(2,F)) : blockHom M ∈ parabolic := by
  have hJ : blockHom (rankOneJ (F := F)) ∈ parabolic := by
    rw [block_rankOneJ]
    apply parabolic.mul_mem (torus_mem_parabolic _ _)
    exact weylR_mem_parabolic
  apply Matrix.SL2.transvection_induction (fun M => blockHom M ∈ parabolic) ?_ ?_ M
  · intro i j hij a
    fin_cases i <;> fin_cases j
    · exact (hij rfl).elim
    · change blockHom (upperSL a) ∈ parabolic
      rw [block_upper]
      exact rootE_mem_parabolic a
    · change blockHom (lowerSL a) ∈ parabolic
      rw [lowerSL_conjugate,map_mul,map_mul,map_inv,block_upper]
      exact parabolic.mul_mem (parabolic.mul_mem hJ (rootE_mem_parabolic _))
        (parabolic.inv_mem hJ)
    · exact (hij rfl).elim
  · intro A B hA hB
    rw [map_mul]
    exact parabolic.mul_mem hA hB

theorem fixingPair_le_parabolic : fixingPair (F := F) ≤ parabolic := by
  intro g hg
  let p : fixingPair (F := F) := ⟨g,hg⟩
  have he := congrArg Subtype.val (block_imageSL p)
  change blockHom (imageSL p) = g at he
  rw [← he]
  exact block_mem_parabolic _

theorem fixingFirstVector_le_parabolic : fixingFirstVector (K := F) ≤ parabolic := by
  intro g hg
  let p : fixingFirstVector (K := F) := ⟨g,hg⟩
  have hn := fixingPair_le_parabolic (normalizedPair p).prop
  have hs := unipotent_le_parabolic (chartReducer_mem_unipotent (partnerOf p).val)
  have h := parabolic.mul_mem (parabolic.inv_mem hs) hn
  change (chartReducer (partnerOf p).val)⁻¹ *
    ((chartReducer (partnerOf p).val) * g) ∈ parabolic at h
  simpa only [inv_mul_cancel_left] using h


theorem unipotent_le_fixingFirstVector : unipotent (K := F) ≤ fixingFirstVector := by
  intro g hg
  rw [unipotent_eq_range] at hg
  obtain ⟨t,rfl⟩ := hg
  change (unipotentProduct t).val (basisVector 0) = basisVector 0
  funext i
  fin_cases i <;> simp [unipotentProduct,basisVector,rootA,rootB,rootC,rootD,rootE,rootF,
    rootAEquiv,rootBEquiv,rootCEquiv,rootDEquiv,rootEEquiv,rootFEquiv,
    rootALinear,rootBLinear,rootCLinear,rootDLinear,rootELinear,rootFLinear,
    rootAApply,rootBApply,rootCApply,rootDApply,rootEApply,rootFApply]

theorem fixingFirstVector_le_pointStabilizer : fixingFirstVector (K := F) ≤ pointStabilizer := by
  intro g hg
  exact (mem_pointStabilizer_iff g).mpr ⟨1,by simpa using (show g.val (basisVector 0) = basisVector 0 from hg)⟩

theorem parabolic_le_pointStabilizer : parabolic (F := F) ≤ pointStabilizer := by
  apply sup_le
  · apply sup_le
    · exact le_trans unipotent_le_fixingFirstVector fixingFirstVector_le_pointStabilizer
    · rintro g ⟨⟨a,b⟩,rfl⟩
      exact (mem_pointStabilizer_iff _).mpr ⟨a,by
        simpa [Units.smul_def,torusHom] using torus_first_basis a b⟩
  · apply (Subgroup.closure_le _).mpr
    rintro g (rfl : g = weylR)
    apply (mem_pointStabilizer_iff _).mpr
    refine ⟨-1,?_⟩
    funext i
    fin_cases i <;> simp [weylR,weylREquiv,weylRLinear,weylRApply,basisVector]

/-- The displayed parabolic is the full stabilizer in the actual octonion automorphism group. -/
theorem parabolic_eq_pointStabilizer : parabolic (F := F) = pointStabilizer := by
  apply le_antisymm parabolic_le_pointStabilizer
  intro g hg
  let p : pointStabilizer (K := F) := ⟨g,hg⟩
  have hn := fixingFirstVector_le_parabolic (normalizePoint p).property
  have ht := torus_mem_parabolic (lineScalar p) 1
  have h := parabolic.mul_mem ht hn
  change (torus (lineScalar p) 1) * ((torus (lineScalar p) 1)⁻¹*g) ∈ parabolic at h
  simpa only [mul_inv_cancel_left] using h

theorem card_parabolic [Finite F] : Nat.card (parabolic (F := F)) =
    Nat.card F ^ 6 * (Nat.card F - 1)^2 * (Nat.card F + 1) := by
  rw [parabolic_eq_pointStabilizer,card_pointStabilizer,Atlas.card_sl_two]
  let q := Nat.card F
  have hq : 1 < q := Finite.one_lt_card (α := F)
  have hq2 : 1 ≤ q^2 := by nlinarith
  have hs := Nat.sub_add_cancel (show 1 ≤ q by omega)
  have hs2 := Nat.sub_add_cancel hq2
  have he : q^2-1 = (q-1)*(q+1) := by nlinarith
  change (q-1)*(q^5*(q*(q^2-1))) = q^6*(q-1)^2*(q+1)
  rw [he]
  ring

theorem borel_relIndex_parabolic [Finite F] :
    (borel (K := F)).relIndex parabolic = Nat.card F + 1 := by
  have hle : borel (K := F) ≤ parabolic := le_sup_left
  have hc := (borel.subgroupOf (parabolic (F := F))).card_mul_index
  rw [Nat.card_congr (Subgroup.subgroupOfEquivOfLe hle).toEquiv,card_borel,card_parabolic] at hc
  change (Nat.card F ^ 6 * (Nat.card F - 1)^2) * borel.relIndex parabolic = _ at hc
  have hq : 1 < Nat.card F := Finite.one_lt_card (α := F)
  have hqm : 0 < Nat.card F - 1 := Nat.sub_pos_of_lt hq
  exact Nat.eq_of_mul_eq_mul_left (by positivity : 0 < Nat.card F ^ 6 * (Nat.card F-1)^2) hc

/-- Explicit scalar, partner-chart and rank-one coordinates on the full parabolic.
This is a bijection of normal-form parameters, not an assertion of a direct-product group law. -/
def parabolicNormalForm : parabolic (F := F) ≃ Fˣ × ((Fin 5 → F) × SL(2,F)) :=
  (MulEquiv.subgroupCongr parabolic_eq_pointStabilizer).toEquiv |>.trans
    (pointStabilizerEquiv.trans (Equiv.prodCongr (Equiv.refl _) 
      (fixingFirstVectorEquivPartners.trans (Equiv.prodCongr
        (singularPartnersEquiv F) fixingPairEquivSL2.toEquiv))))

end Atlas.G2
