import Atlas.Algebra.IcosianDivision
import Atlas.Algebra.IcosianNormTwoAssociates

set_option backward.isDefEq.respectTransparency false
namespace Atlas.Algebra
open scoped Quaternion

/-- The orthogonal complement of (r,s), with both coordinate norms two,
is the right quaternionic line generated by (r,-s). -/
theorem icosianNormTwoPair_orthogonal (r s x y : IcosianQuaternion)
    (hr : icosianNorm r=2) (hs : icosianNorm s=2)
    (h : star r*x+star s*y=0) :
    ∃ a : IcosianQuaternion,x=r*a ∧ y=(-s)*a := by
  have hn : r≠0 := by intro hh; rw [hh] at hr; norm_num [icosianNorm] at hr
  let a := r⁻¹*x
  have hx : x=r*a := by simp [a,mul_assoc,hn]
  have hrr : star r*r=(2 : IcosianQuaternion) := by
    rw [Quaternion.star_mul_self]; change (icosianNorm r : IcosianQuaternion)=2
    rw [hr]; rfl
  have hss : s*star s=(2 : IcosianQuaternion) := by
    rw [Quaternion.self_mul_star]; change (icosianNorm s : IcosianQuaternion)=2
    rw [hs]; rfl
  have he : star s*y=-(2*a) := by
    rw [hx,← mul_assoc,hrr] at h
    exact eq_neg_of_add_eq_zero_right h
  have hh := congrArg (s*·) he
  rw [← mul_assoc,hss] at hh
  have h2 : (2 : IcosianQuaternion)≠0 := by
    intro hz
    have ht := congrArg (fun z : IcosianQuaternion => z.re.re) hz
    norm_num [QuaternionAlgebra.re_ofNat,QuadraticAlgebra.re_ofNat] at ht
  refine ⟨a,hx,mul_left_cancel₀ h2 ?_⟩
  calc
    2*y=s*(-(2*a)) := hh
    _=2*((-s)*a) := by noncomm_ring

end Atlas.Algebra
