import Mathlib.Algebra.Group.TypeTags.Finite
import Mathlib.Algebra.Group.Subgroup.Pointwise
import Mathlib.Algebra.Group.Subgroup.Ker
import Mathlib.Data.ZMod.Basic

noncomputable section
namespace Atlas.Algebra

/-- If involutions of odd binary parity generate a group, the parity kernel
is generated by their pairwise products. The proof is direct word induction,
with no finiteness, index, normality or perfectness premise. -/
theorem involutive_parity_kernel_generated_pairs {G I : Type*} [Group G]
    (s : I → G) (i0 : I) (hs : ∀ i, s i * s i=1)
    (φ : G →* Multiplicative (ZMod 2))
    (hφ : ∀ i, φ (s i)=Multiplicative.ofAdd (1 : ZMod 2))
    (hgen : Subgroup.closure (Set.range s)=⊤) :
    φ.ker = Subgroup.closure (Set.range (fun ij : I × I => s ij.1 * s ij.2)) := by
  let H : Subgroup G := Subgroup.closure (Set.range (fun ij : I × I => s ij.1 * s ij.2))
  let o : Multiplicative (ZMod 2) := Multiplicative.ofAdd 1
  have ho : o * o=1 := by decide
  have hno : o ≠ 1 := by decide
  have hvalues (a : Multiplicative (ZMod 2)) : a=1 ∨ a=o := by
    have h : ∀ a : Multiplicative (ZMod 2), a=1 ∨ a=Multiplicative.ofAdd (1 : ZMod 2) := by decide
    exact h a
  have hpair (i j : I) : s i * s j ∈ H := Subgroup.subset_closure ⟨(i,j),rfl⟩
  let P : G → Prop := fun g => (φ g=1 → g ∈ H) ∧ (φ g=o → s i0 * g ∈ H)
  have hone : P 1 := by
    constructor
    · intro _
      exact H.one_mem
    · intro h
      exact (hno (h.symm.trans φ.map_one)).elim
  have hstep (i : I) (y : G) (hy : P y) : P (s i * y) := by
    rcases hvalues (φ y) with hz | hz
    · constructor
      · intro h
        rw [map_mul,hφ,hz,mul_one] at h
        exact (hno h).elim
      · intro _
        have hm := H.mul_mem (hpair i0 i) (hy.1 hz)
        simpa only [mul_assoc] using hm
    · constructor
      · intro _
        have hm := H.mul_mem (hpair i i0) (hy.2 hz)
        have hc : (s i * s i0) * (s i0 * y)=s i * y := by
          rw [mul_assoc,← mul_assoc (s i0) (s i0) y,hs,one_mul]
        rw [hc] at hm
        exact hm
      · intro h
        rw [map_mul,hφ,hz] at h
        change o * o=o at h
        rw [ho] at h
        exact (hno h.symm).elim
  have hall (g : G) : P g := by
    have hg : g ∈ Subgroup.closure (Set.range s) := by rw [hgen]; trivial
    apply Subgroup.closure_induction_left (p := fun g _ => P g) hone ?_ ?_ hg
    · rintro x ⟨i,rfl⟩ y _ hy
      exact hstep i y hy
    · rintro x ⟨i,rfl⟩ y _ hy
      have hi : (s i)⁻¹=s i := inv_eq_of_mul_eq_one_right (hs i)
      simpa only [hi] using hstep i y hy
  apply le_antisymm
  · intro g hg
    exact (hall g).1 hg
  · apply (Subgroup.closure_le _).mpr
    rintro x ⟨⟨i,j⟩,rfl⟩
    change φ (s i * s j)=1
    rw [map_mul,hφ,hφ]
    exact ho

end Atlas.Algebra
