import Atlas.Codes.IcosianGlueMonomial

set_option backward.isDefEq.respectTransparency false
noncomputable section
namespace Atlas.Codes
open Matrix

theorem icosianGlueBlockParameter_unipotent_mul {F : Type*} [Field F]
    (a b c d : F) :
    icosianGlueBlockParameter (1 : Fˣ) a b *
      icosianGlueBlockParameter (1 : Fˣ) c d=
        icosianGlueBlockParameter (1 : Fˣ) (a+c) (b+d) := by
  funext i
  apply Subtype.ext
  change (icosianGlueBlockParameter (1 : Fˣ) a b i).val *
    (icosianGlueBlockParameter (1 : Fˣ) c d i).val=
      (icosianGlueBlockParameter (1 : Fˣ) (a+c) (b+d) i).val
  ext j k
  fin_cases i <;> fin_cases j <;> fin_cases k <;>
    simp [icosianGlueBlockParameter,icosianGlueMatrix,Matrix.SpecialLinearGroup.coe_mul,Matrix.mul_apply,Fin.sum_univ_succ] <;> ring

theorem icosianGlueBlockParameter_decompose {F : Type*} [Field F]
    (s : Fˣ) (a b : F) :
    icosianGlueBlockParameter s a b=
      icosianGlueBlockParameter s 0 0 *
        (icosianGlueBlockParameter (1 : Fˣ) ((s : F)*a) 0 *
          icosianGlueBlockParameter (1 : Fˣ) 0 ((s : F)*b)) := by
  rw [icosianGlueBlockParameter_unipotent_mul]
  funext i
  apply Subtype.ext
  change (icosianGlueBlockParameter s a b i).val=
    (icosianGlueBlockParameter s 0 0 i).val *
      (icosianGlueBlockParameter (1 : Fˣ) ((s : F)*a+0) (0+(s : F)*b) i).val
  ext j k
  fin_cases i <;> fin_cases j <;> fin_cases k <;>
    simp [icosianGlueBlockParameter,icosianGlueMatrix,Matrix.SpecialLinearGroup.coe_mul,Matrix.mul_apply,Fin.sum_univ_succ,
      Units.ne_zero s] <;> field_simp <;> ring

/-- The complete glue stabilizer is generated by its two paired unipotent
families, the common diagonal scalars, and the coordinate permutations. -/
theorem icosianGlueMonomialStabilizer_le_of_generators {F : Type*} [Field F] [Finite F]
    (H : Subgroup (IcosianGlueMonomialGroup F))
    (hD : ∀ s : Fˣ, SemidirectProduct.inl (icosianGlueBlockParameter s 0 0)∈H)
    (hU : ∀ a : F, SemidirectProduct.inl (icosianGlueBlockParameter 1 a 0)∈H)
    (hV : ∀ b : F, SemidirectProduct.inl (icosianGlueBlockParameter 1 0 b)∈H)
    (hP : ∀ p : Equiv.Perm (Fin 3), SemidirectProduct.inr p∈H) :
    icosianGlueMonomialStabilizer F≤H := by
  intro g hg
  let b : icosianGlueBlockStabilizer F :=
    ⟨g.left,(icosianGlueMonomialStabilizer_iff g).mp hg⟩
  obtain ⟨⟨s,a,c⟩,he⟩ := icosianGlueBlockParameterElement_surjective b
  have hb : icosianGlueBlockParameter s a c=g.left := congrArg Subtype.val he
  have hblock : SemidirectProduct.inl g.left∈H := by
    rw [← hb,icosianGlueBlockParameter_decompose,map_mul,map_mul]
    exact H.mul_mem (hD s) (H.mul_mem (hU _) (hV _))
  have hg' : g=SemidirectProduct.inl g.left*SemidirectProduct.inr g.right := by
    apply SemidirectProduct.ext <;> simp
  rw [hg']
  exact H.mul_mem hblock (hP _)

end Atlas.Codes
