# Local metadata gate: no builds, downloads, pushes or visibility changes.
require 'json'
require 'digest'
require 'csv'
require 'pathname'
Dir.chdir(File.expand_path('..', __dir__))
mode = ARGV.fetch(0, 'check')
abort 'Usage: ruby verification/release_metadata.rb [refresh|check]' unless %w[refresh check].include?(mode)
def read_json(p) = JSON.parse(File.read(p))
def sha(p) = Digest::SHA256.file(p).hexdigest
def require_equal(actual, expected, message)
  raise message unless actual == expected
end
begin
  raise 'Obsolete docs directory; use catalogue/' if Dir.exist?('docs')
  index = read_json('verification/current.json')
  snapshot = index.fetch('snapshot')
  raise 'Unsafe evidence path' unless snapshot.match?(%r{\Averification/[a-zA-Z0-9_-]+\z})
  index.fetch('evidence_files').each do |p, h|
    raise 'Unsafe evidence filename' unless File.basename(p) == p
    require_equal(sha("#{snapshot}/#{p}"), h, "Changed evidence: #{p}")
  end
  sources = (Dir.glob('Atlas/**/*.lean') + %w[Atlas.lean lean-toolchain lakefile.toml lake-manifest.json]).sort.to_h { |p| [p, sha(p)] }
  require_equal(sources, read_json("#{snapshot}/SOURCE_HASHES.json"), 'Stale verification: sources/pins changed; complete and record new checks first')
  roots = read_json('verification/roots.json')
  require_equal(roots, read_json("#{snapshot}/roots.json"), 'Verification target set changed; new evidence required')
  catalogue = read_json('catalogue/catalogue.json')
  names = []
  walk = lambda do |x|
    case x
    when Hash
      names << x['declaration'] if x['declaration'] && x['source']
      x.each_value { |v| walk.call(v) }
    when Array then x.each { |v| walk.call(v) }
    end
  end
  walk.call(catalogue)
  require_equal(names.uniq.sort, roots.map { |r| r.fetch('declaration') }.sort, 'Catalogue and audited targets differ')
  build, nanoda, comparator = %w[build nanoda comparator].map { |k| read_json("#{snapshot}/#{k}.json") }
  [build, nanoda, comparator].each do |r|
    require_equal(r['status'], 'passed', 'Unsuccessful verification record')
    require_equal(r['roots'], roots.size, 'Verification root count mismatch')
    axioms = r['axioms'] || r['allowed_axioms']
    raise 'Unapproved axiom' unless axioms && (axioms - %w[propext Classical.choice Quot.sound]).empty?
  end
  require_equal(comparator['exit_code'], 0, 'Comparator exit status')
  require_equal(comparator['definition_holes'], 0, 'Comparator has definition holes')
  targets = read_json("#{snapshot}/comparator-targets.json")
  require_equal(targets.map { |r| r['original'] }.sort, names.uniq.sort, 'Comparator target mismatch')
  measurement = read_json('catalogue/measurement.json')
  require_equal(measurement['compatible_source_hashes'], sources.select { |p, _| p.end_with?('.lean') }, 'Stale line counts; remeasure changed sources')
  require_equal(measurement['csv_sha256'], sha('catalogue/proof-line-counts.csv'), 'Line-count CSV changed without measurement record')
  rows = CSV.read('catalogue/proof-line-counts.csv', headers: true)
  catalogue.fetch('entries').each do |e|
    # Measurements may use the stronger exact-exception iff theorem listed
    # among an entry's properties, rather than its positive-range wrapper.
    allowed = [e.dig('roles','simple','declaration')] + e.fetch('properties', []).map { |p| p['declaration'] }
    row = rows.find { |r| r['order_root'] == e.dig('roles','order','declaration') && allowed.include?(r['simplicity_root']) }
    raise "Missing order/simplicity counts: #{e['id']}" unless row
    anchor = e.fetch('id').downcase.tr('.', '-')
    line = File.readlines('CATALOGUE.md').find { |l| l.start_with?('| [') && l.include?("](##{anchor})") }
    raise "Missing catalogue summary row: #{e['id']}" unless line
    displayed = line.strip.split('|').last(3).map { |v| v.delete(',').strip }
    expected = %w[atlas_order_lines atlas_simplicity_lines atlas_union_lines].map { |k| row.fetch(k) }
    require_equal(displayed, expected, "Stale summary counts: #{e['id']}")
  end
  raise 'Missing PDF' unless File.binread('atlas_research_note.pdf', 5) == '%PDF-'
  raise 'Missing PDF entry link' unless File.read('README.md').include?('](atlas_research_note.pdf)')
  raise 'Unexpected release license' unless File.read('LICENSE').include?('ATLAS Research and Attribution License')
  raise 'Outdated Apache citation' if File.read('CITATION.cff').include?('license: Apache-2.0')
  nanoda_time = File.read("#{snapshot}/nanoda-check.time")[/Elapsed .*?: ([0-9:.]+)$/, 1] or raise 'Missing Nanoda timing'
  audit = <<~MD
    # Verification of this release

    <!-- Generated by verification/release_metadata.rb; do not edit by hand. -->
    The mathematical source snapshot at commit `#{index.fetch('source_commit')}` passed
    all three checks below. Current source and dependency-pin hashes match that snapshot;
    subsequent documentation-only commits do not change the checked mathematics.

    | Check | Successful result | Evidence |
    |---|---|---|
    | Lean project build and dependency audit | #{build['roots']} selected roots; #{build['dependency_nodes']} transitive dependency nodes | [Build/audit](#{snapshot}/build.json) |
    | Independent Nanoda replay | #{nanoda['checked_declarations']} exported declarations, no errors; #{nanoda_time} elapsed | [Nanoda](#{snapshot}/nanoda.json), [timing](#{snapshot}/nanoda-check.time) |
    | Comparator | #{comparator['roots']} targets; statement/definition comparison, axiom check and Lean kernel replay passed; #{comparator['service_runtime']} | [Comparator](#{snapshot}/comparator.json), [verdict](#{snapshot}/comparator-verdict.txt) |

    The only allowed logical axioms are `propext`, `Classical.choice`, and `Quot.sound`.
    The [target list](verification/roots.json) includes catalogue, structural and comparison
    declarations. Counts from the graph audit and export checker measure different artifacts.
    These are not counts of groups, and unrelated imported library theorems are outside the selection.

    The project build used pinned dependency caches: it was not a fresh source rebuild of
    all mathlib. Nanoda independently checked the exported dependency closure.
    Comparator used the same frozen formal development as both reference and solution,
    with #{comparator['theorems']} theorem targets and #{comparator['definition_wrappers']} definition wrappers,
    no definition holes, the real Landrun sandbox and standard Lean kernel replay.
    It was not comparison with an independently authored mathematical specification.
    Nanoda was a separate run. These checks still rely on foundations and the host/toolchain.

    The current evidence summaries, target mapping and source hashes are under
    [#{snapshot}](#{snapshot}/). Original export-build evidence remains under
    [verification/release](verification/release/); it is historical and has not been overwritten.
    Large raw proof exports and host-specific operational logs are not distributed here.

    ## Reproduce the Lean build and dependency audit

    ```sh
    lake exe cache get
    LEAN_NUM_THREADS=2 ruby verification/check.rb
    ```

    This builds the project and writes new compiled statements, transitive type/proof
    dependency records and hashes under ignored `verification/results/`. It does not
    run Nanoda or Comparator, or automatically promote new evidence to release status.
    Use one build/audit driver at a time. Existing style warnings are not proof placeholders;
    the transitive trust audit rejects unapproved axioms and native-reduction shortcuts.

    ## Release maintenance

    Run `ruby verification/release_metadata.rb refresh` after documentation changes,
    then `ruby verification/release_metadata.rb check`. This checks catalogue targets,
    evidence/source compatibility, line-count provenance, local documentation links and
    release checksums. It refuses to reuse this evidence after mathematical sources or
    pins change. See [maintenance instructions](verification/MAINTENANCE.md).
    These consistency checks do not rerun proofs or cryptographically attest execution.
  MD
  if mode == 'refresh'
    File.write('AUDIT.md', audit)
  else
    require_equal(File.read('AUDIT.md'), audit, 'Stale AUDIT.md; run metadata refresh')
  end
  Dir.glob('*.md').each do |p|
    s = File.read(p)
    raise "Obsolete catalogue link in #{p}" if s.match?(%r{docs/(catalogue.json|proof-line-counts.csv)})
    s.scan(/\]\(([^)]+)\)/).flatten.each do |link|
      next if link.match?(%r{\A(?:https?://|#|\.lake/)})
      target = link.split('#').first
      raise "Broken local link #{p}: #{target}" unless target && File.exist?(target)
    end
  end
  paths = (%w[.gitignore README.md CATALOGUE.md AUDIT.md CITATION.cff LICENSE LICENSING.md Atlas.lean lean-toolchain lakefile.toml lake-manifest.json atlas_research_note.pdf] + Dir.glob('Atlas/**/*.lean') + Dir.glob('catalogue/*') + Dir.glob('verification/**/*').select { |p| File.file?(p) && !p.start_with?('verification/results/') }).sort
  paths.each { |p| raise "Symlink #{p}" if File.symlink?(p) }
  hashes = paths.to_h { |p| [p, sha(p)] }
  manifest = {'format'=>1, 'toolchain'=>File.read('lean-toolchain').strip, 'dependencies'=>read_json('lake-manifest.json'), 'roots'=>'verification/roots.json', 'verification'=>'verification/current.json', 'files'=>hashes}
  manifest_text = JSON.pretty_generate(manifest) + "\n"
  checksums = hashes.merge('RELEASE_MANIFEST.json'=>Digest::SHA256.hexdigest(manifest_text)).sort.map { |p,h| "#{h}  #{p}\n" }.join
  if mode == 'refresh'
    File.write('RELEASE_MANIFEST.json', manifest_text)
    File.write('SHA256SUMS', checksums)
  else
    require_equal(File.read('RELEASE_MANIFEST.json'), manifest_text, 'Stale release manifest')
    require_equal(File.read('SHA256SUMS'), checksums, 'Stale release checksums')
  end
  puts "PASS: release layout, #{roots.size} targets, source-bound evidence, line counts, links and checksums (#{mode})."
rescue StandardError => e
  warn "Release check refused: #{e.message}"
  exit 1
end
