import Atlas.Fischer.SemilinearFrameRecovery
import Mathlib.Tactic.Group

noncomputable section
namespace Atlas.Fischer

/-- Frame conjugacy and the proved full frame stabilizer imply that every
actual semilinear algebra automorphism is generated by the root reflections. -/
theorem semilinearAlgebra_mem_generated (e : SemilinearAlgebraAutomorphism) :
    e ∈ rootGeneratedAlgebraGroup := by
  obtain ⟨g,hg⟩ := fischerFrame_standard_conjugate
    (semilinearGeneratedConjugation e '' standardCommutingFrame) (semilinear_standard_image_isFrame e)
  obtain ⟨E,hE⟩ := rootGeneratedRayGroup_lift g
  let f : SemilinearAlgebraAutomorphism := E.val⁻¹*e
  have hf : f ∈ basicFrameStabilizer := by
    apply semilinear_mem_basicFrame_of_class_image
    rintro x ⟨y,hy,rfl⟩
    have hm : semilinearGeneratedConjugation e y ∈
        (MulAut.conj g) '' standardCommutingFrame := by
      rw [hg]
      exact ⟨y,hy,rfl⟩
    obtain ⟨z,hz,hze⟩ := hm
    have heq : semilinearGeneratedConjugation f y=z := by
      apply Subtype.ext
      have hv := congrArg Subtype.val hze
      change g.val*z.val*g.val⁻¹=
        semilinearDisplayedRayAction e*y.val*(semilinearDisplayedRayAction e)⁻¹ at hv
      change semilinearDisplayedRayAction (E.val⁻¹*e)*y.val*
        (semilinearDisplayedRayAction (E.val⁻¹*e))⁻¹=z.val
      rw [map_mul,map_inv,hE]
      calc
        (g.val⁻¹*semilinearDisplayedRayAction e)*y.val*
            (g.val⁻¹*semilinearDisplayedRayAction e)⁻¹ =
          g.val⁻¹*(semilinearDisplayedRayAction e*y.val*(semilinearDisplayedRayAction e)⁻¹)*g.val := by group
        _ = g.val⁻¹*(g.val*z.val*g.val⁻¹)*g.val := by rw [← hv]
        _ = z.val := by group
    exact heq ▸ hz
  have hm := rootGeneratedAlgebraGroup.mul_mem E.property (basicFrameStabilizer_le_generated hf)
  change E.val*(E.val⁻¹*e) ∈ rootGeneratedAlgebraGroup at hm
  simpa only [mul_inv_cancel_left] using hm

theorem rootGeneratedAlgebraGroup_eq_top : rootGeneratedAlgebraGroup=⊤ := by
  apply top_unique
  intro e _
  exact semilinearAlgebra_mem_generated e

/-- The full semilinear ray image equals the actually root-generated group. -/
theorem semilinearDisplayedRayAction_range :
    semilinearDisplayedRayAction.range=rootGeneratedRayGroup := by
  rw [MonoidHom.range_eq_map,← rootGeneratedAlgebraGroup_eq_top,
    rootGeneratedAlgebraGroup_ray_image]

end Atlas.Fischer
