import Atlas.Fischer.GeneratedAlgebraParity
import Atlas.Fischer.RayKernelScalarRigidity

noncomputable section
namespace Atlas.Fischer
open Atlas.Codes

/-- Restrict the actual ray action to the generated algebra and ray subgroups. -/
def rootGeneratedRayProjection : rootGeneratedAlgebraGroup →* rootGeneratedRayGroup :=
  (semilinearDisplayedRayAction.comp rootGeneratedAlgebraGroup.subtype).codRestrict rootGeneratedRayGroup
    (fun e => by
      rw [← rootGeneratedAlgebraGroup_ray_image]
      exact ⟨e.val,e.property,rfl⟩)

theorem rootGeneratedRayProjection_surjective : Function.Surjective rootGeneratedRayProjection := by
  intro g
  obtain ⟨e,he⟩ := rootGeneratedRayGroup_lift g
  exact ⟨e,Subtype.ext he⟩

theorem rootGeneratedRayProjection_kernel_parity :
    rootGeneratedRayProjection.ker ≤ rootGeneratedAlgebraParity.ker := by
  intro e he
  have hker : e.val ∈ semilinearRayKernel := by
    change semilinearDisplayedRayAction e.val=1
    exact congrArg Subtype.val he
  have hp := semilinearRayKernel_parity_zero e.val hker
  change Multiplicative.ofAdd (semilinearAlgebraParity e.val)=1
  rw [hp]
  rfl

/-- Binary parity descends through the actual scalar kernel. It is not a
second tag attached to the ray permutation. -/
def rootGeneratedRayParity : rootGeneratedRayGroup →* Multiplicative Bit :=
  rootGeneratedRayProjection.liftOfSurjective rootGeneratedRayProjection_surjective
    ⟨rootGeneratedAlgebraParity,rootGeneratedRayProjection_kernel_parity⟩

theorem rootGeneratedRayParity_projection (e : rootGeneratedAlgebraGroup) :
    rootGeneratedRayParity (rootGeneratedRayProjection e)=rootGeneratedAlgebraParity e := by
  simp [rootGeneratedRayParity,MonoidHom.liftOfSurjective]

theorem distinguishedRootElement_parity (t : ReflectingRootParameter) :
    rootGeneratedRayParity (distinguishedRootElement t)=Multiplicative.ofAdd (1 : Bit) := by
  change rootGeneratedRayParity (rootGeneratedRayProjection (displayedAlgebraRootElement t))=_
  rw [rootGeneratedRayParity_projection,displayedAlgebraRootElement_parity]

theorem distinguishedRootElement_mul_self (t : ReflectingRootParameter) :
    distinguishedRootElement t * distinguishedRootElement t=1 := by
  apply Subtype.ext
  exact (pow_two (displayedRootRayInvolution t)).symm.trans (displayedRootRayInvolution_square t)

/-- The positive ray subgroup is generated by the actual pair products. -/
theorem rootGeneratedRayParity_kernel_pairs : rootGeneratedRayParity.ker =
    Subgroup.closure (Set.range (fun ij : ReflectingRootParameter × ReflectingRootParameter =>
      distinguishedRootElement ij.1 * distinguishedRootElement ij.2)) :=
  Atlas.Algebra.involutive_parity_kernel_generated_pairs distinguishedRootElement
    (.inl (Classical.arbitrary Omega)) distinguishedRootElement_mul_self rootGeneratedRayParity
    distinguishedRootElement_parity distinguishedRootClass_generates

theorem rootGeneratedRayParity_surjective : Function.Surjective rootGeneratedRayParity := by
  intro b
  obtain ⟨e,he⟩ := rootGeneratedAlgebraParity_surjective b
  exact ⟨rootGeneratedRayProjection e,(rootGeneratedRayParity_projection e).trans he⟩

end Atlas.Fischer
