import Atlas.Fischer.ResidueGeneratedFrames

noncomputable section
namespace Atlas.Fischer
open Atlas.Codes

theorem standardCommutingFrame_le_residueGenerated (S : Finset Omega) :
    standardCommutingFrame ⊆ residueGenerated S :=
  fischerFrame_le_residueGenerated S standardCommutingFrame
    standardCommutingFrame_isFrame (by rintro x ⟨i,hi,rfl⟩; exact ⟨i,rfl⟩)

theorem generatedCocodeRayHom_basic (i : Omega) :
    generatedCocodeRayHom (cocodeInvolution i)=distinguishedRootElement (.inl i) := by
  apply Subtype.ext
  exact cocodeRayHom_basic i

/-- The entire literal frame kernel is already generated by the involutions
available in every marked residue. -/
theorem basicFramePointwiseRayStabilizer_le_residueGenerated (S : Finset Omega) :
    basicFramePointwiseRayStabilizer ≤ residueGenerated S := by
  rw [basicFramePointwiseRayStabilizer_eq_cocode,MonoidHom.range_eq_map,
    ← cocodeInvolutions_generate,MonoidHom.map_closure]
  apply (Subgroup.closure_le _).mpr
  rintro x ⟨y,⟨i,rfl⟩,rfl⟩
  rw [generatedCocodeRayHom_basic]
  exact standardCommutingFrame_le_residueGenerated S ⟨i,rfl⟩

end Atlas.Fischer
