import Atlas.Fischer.ResidueFullFrameStabilizer

noncomputable section
namespace Atlas.Fischer
open Atlas.Codes

/-- The actual centralizer is generated by its marked involutions and its
remaining distinguished involutions. Both the local frame stabilizer and the
conjugating elements have been proved to lie in that generated subgroup. -/
theorem residueGenerated_eq_centralizer (S : Finset Omega) (hS : S.card ≤ 2) :
    residueGenerated S=residueCentralizer S := by
  apply le_antisymm (residueGenerated_le_centralizer S)
  intro g hg
  let F := standardCommutingFrame
  have hF : IsFischerFrame F := standardCommutingFrame_isFrame
  have hSF : residueBasicSet S ⊆ F := by
    rintro x ⟨i,hi,rfl⟩
    exact ⟨i,rfl⟩
  have hK : IsFischerFrame ((MulAut.conj g) '' F) :=
    hF.image _ (distinguishedRootClass_conjugation g)
  have hSK : residueBasicSet S ⊆ (MulAut.conj g) '' F := by
    rintro x ⟨i,hi,rfl⟩
    exact ⟨distinguishedRootElement (.inl i),⟨i,rfl⟩,
      (mem_markedPentadPointwise_iff S g).mp hg i hi⟩
  obtain ⟨a,ha⟩ := residueGenerated_frames_conjugate S F _ hF hK hSF hSK
  have hn : a.val⁻¹*g ∈ standardFrameRayStabilizer := by
    apply Subgroup.mem_normalizer_iff_conj_image_eq.mpr
    change (MulAut.conj (a.val⁻¹*g)) '' F=F
    calc
      _ = (MulAut.conj a.val⁻¹) '' ((MulAut.conj g) '' F) := by
        rw [Set.image_image]
        congr 1
      _ = (MulAut.conj a.val⁻¹) '' ((MulAut.conj a.val) '' F) := by rw [ha]
      _ = F := by
        rw [Set.image_image]
        have he : (fun x => (MulAut.conj a.val⁻¹) ((MulAut.conj a.val) x))=id := by
          funext x
          simp [Function.comp_def,MulAut.conj_apply,mul_assoc]
        rw [he,Set.image_id]
  have hc : a.val⁻¹*g ∈ residueCentralizer S :=
    (residueCentralizer S).mul_mem
      ((residueCentralizer S).inv_mem (residueGenerated_le_centralizer S a.property)) hg
  have hm := (residueGenerated S).mul_mem a.property
    (residueMarkedFrame_le_generated S hS ⟨hn,hc⟩)
  simpa only [mul_inv_cancel_left] using hm

end Atlas.Fischer
