import Atlas.Fischer.ResidueModels
import Atlas.Fischer.FischerFrameAction
import Atlas.GroupTheory.CommutingFrameRestriction

noncomputable section
namespace Atlas.Fischer
open Atlas.Codes

/-- The subgroup generated by the marked involutions and the actual remaining
involutions commuting with them, before taking a central quotient. -/
def residueGenerated (S : Finset Omega) : Subgroup rootGeneratedRayGroup :=
  Subgroup.closure (residueBasicSet S ∪ Set.range (fun x : ResiduePoint S => x.val))

theorem residueElementary_le_generated (S : Finset Omega) :
    residueElementary S ≤ residueGenerated S :=
  Subgroup.closure_mono Set.subset_union_left

theorem residueGenerated_le_centralizer (S : Finset Omega) :
    residueGenerated S ≤ residueCentralizer S := by
  apply (Subgroup.closure_le _).mpr
  intro x hx
  rcases hx with hx | ⟨r,rfl⟩
  · exact residueElementary_le_centralizer S (Subgroup.subset_closure hx)
  · rintro y ⟨i,hi,rfl⟩
    exact (r.property.2.2 i hi).eq

theorem fischerFrame_le_residueGenerated (S : Finset Omega)
    (F : Set rootGeneratedRayGroup) (hF : IsFischerFrame F)
    (hSF : residueBasicSet S ⊆ F) : F ⊆ residueGenerated S := by
  intro x hx
  apply Subgroup.subset_closure
  by_cases hm : x ∈ residueBasicSet S
  · exact Or.inl hm
  · right
    refine ⟨⟨x,hF.1 hx,hm,?_⟩,rfl⟩
    intro i hi
    exact hF.2.1 _ (hSF ⟨i,hi,rfl⟩) _ hx

/-- Every pair of full frames through the marking is conjugate by an element
of the residue-generated subgroup itself. -/
theorem residueGenerated_frames_conjugate (S : Finset Omega)
    (F K : Set rootGeneratedRayGroup) (hF : IsFischerFrame F)
    (hK : IsFischerFrame K) (hSF : residueBasicSet S ⊆ F)
    (hSK : residueBasicSet S ⊆ K) :
    ∃ g : residueGenerated S, (MulAut.conj g.val) '' F = K := by
  have hsq : ∀ x ∈ Set.range distinguishedRootElement, x^2=1 := by
    rintro x ⟨i,rfl⟩
    exact orderOf_dvd_iff_pow_eq_one.mp (by rw [distinguishedRootElement_order])
  apply Atlas.GroupTheory.commutingFrames_conjugate_in_subgroup
    (Set.range distinguishedRootElement) F K (residueGenerated S) hsq ?_
    distinguishedRootClass_conjugation hF hK
    (fischerFrame_le_residueGenerated S F hF hSF)
    (fischerFrame_le_residueGenerated S K hK hSK)
  rintro x ⟨i,rfl⟩ y ⟨j,rfl⟩
  by_cases hij : i=j
  · subst j
    left
    rw [← pow_two,hsq _ ⟨i,rfl⟩,one_pow]
  · have hp := distinguishedRootElement_product_order i j hij
    split_ifs at hp with h
    · exact Or.inr hp
    · exact Or.inl (orderOf_dvd_iff_pow_eq_one.mp (by rw [hp]))

end Atlas.Fischer
