import Atlas.Fischer.RootRayTransitivity
import Atlas.Fischer.ReflectionFixedRays

noncomputable section
namespace Atlas.Fischer

/-- A normalized intrinsic reflecting root induces a ray permutation; its
algebra lift retains its scalar phase. -/
def intrinsicRootRayInvolution (r : Coordinates) (hr : IsReflectingRoot r) :
    Equiv.Perm DisplayedReflectingRay := semilinearDisplayedRayAction (reflectingRootAutomorphism r hr)

theorem intrinsicRootRayInvolution_parameter_value (r : Coordinates) (hr : IsReflectingRoot r)
    (t : ReflectingRootParameter) :
    (intrinsicRootRayInvolution r hr (displayedRayOfParameter t)).val =
      rootRay (rootMap r (reflectingRootParameterVector t)) :=
  semilinearDisplayedRayAction_parameter_value _ _

/-- The output permutation depends only on the actual normalized root ray. -/
theorem intrinsicRootRayInvolution_eq_of_ray (r s : Coordinates)
    (hr : IsReflectingRoot r) (hs : IsReflectingRoot s) (he : rootRay r=rootRay s) :
    intrinsicRootRayInvolution r hr=intrinsicRootRayInvolution s hs := by
  obtain ⟨a,ha,he⟩ := (rootRay_eq_iff s r).mp he
  apply Equiv.ext
  intro R
  obtain ⟨t,rfl⟩ := displayedRayOfParameter_surjective R
  apply Subtype.ext
  rw [intrinsicRootRayInvolution_parameter_value,intrinsicRootRayInvolution_parameter_value,
    he,rootMap_phase_ray s _ a ha]

/-- Actual algebra conjugation, before quotienting phases. -/
theorem reflectingRootAutomorphism_conjugation (e : SemilinearAlgebraAutomorphism)
    (r : Coordinates) (hr : IsReflectingRoot r) :
    e * reflectingRootAutomorphism r hr * e⁻¹ =
      reflectingRootAutomorphism (e.val r) (semilinearAlgebra_isReflectingRoot e r hr) := by
  apply Subtype.ext
  apply Equiv.ext
  intro x
  change e.val (rootMap r (e.val.symm x))=rootMap (e.val r) x
  have he := semilinearAlgebra_rootMap e r (e.val.symm x)
  rw [e.val.apply_symm_apply] at he
  exact he.symm

theorem intrinsicRootRayInvolution_conjugation (e : SemilinearAlgebraAutomorphism)
    (r : Coordinates) (hr : IsReflectingRoot r) :
    semilinearDisplayedRayAction e * intrinsicRootRayInvolution r hr *
      (semilinearDisplayedRayAction e)⁻¹ =
        intrinsicRootRayInvolution (e.val r) (semilinearAlgebra_isReflectingRoot e r hr) := by
  rw [intrinsicRootRayInvolution,← map_inv,← map_mul,← map_mul,
    reflectingRootAutomorphism_conjugation]
  rfl

theorem displayedRootRayInvolution_covariance (e : SemilinearAlgebraAutomorphism)
    (i j : ReflectingRootParameter)
    (he : rootRay (e.val (reflectingRootParameterVector i))=reflectingRootParameterRay j) :
    semilinearDisplayedRayAction e * displayedRootRayInvolution i *
      (semilinearDisplayedRayAction e)⁻¹ = displayedRootRayInvolution j := by
  change semilinearDisplayedRayAction e * intrinsicRootRayInvolution _ _ *
    (semilinearDisplayedRayAction e)⁻¹ = intrinsicRootRayInvolution _ _
  rw [intrinsicRootRayInvolution_conjugation]
  exact intrinsicRootRayInvolution_eq_of_ray _ _ _ _ he

/-- Every element of the root-generated ray group lifts to the subgroup
actually generated by the displayed algebra reflections. -/
theorem rootGeneratedRayGroup_lift (g : rootGeneratedRayGroup) :
    ∃ e : rootGeneratedAlgebraGroup, semilinearDisplayedRayAction e.val=g.val := by
  have hg : g.val ∈ rootGeneratedAlgebraGroup.map semilinearDisplayedRayAction := by
    rw [rootGeneratedAlgebraGroup_ray_image]
    exact g.property
  obtain ⟨e,he,hg⟩ := hg
  exact ⟨⟨e,he⟩,hg⟩

end Atlas.Fischer
