import Atlas.Fischer.CocodeCoordinates
import Mathlib.LinearAlgebra.LinearIndependent.Lemmas

noncomputable section
namespace Atlas.Fischer
open Atlas.Codes

/-- No nonempty set of fewer than eight marked coordinates is a cocode relation. -/
theorem coordinateCocode_small_sum_eq_zero (S : Finset Omega) (hS : S.card<8) :
    (∑ i ∈ S,coordinateCocode i)=0 ↔ S=∅ := by
  classical
  rw [coordinateCocode_sum_eq_zero]
  constructor
  · intro h
    by_contra hn
    have hw : binarySupportEquiv.symm S ≠ (0 : BinaryWord) := by
      intro hz
      have hs := congrArg binarySupportEquiv hz
      exact hn (by simpa [binarySupportEquiv,support] using hs)
    have hm := golay_minimum _ h hw
    have he : hammingNorm (binarySupportEquiv.symm S)=S.card := by
      change (binarySupportEquiv (binarySupportEquiv.symm S)).card=S.card
      rw [Equiv.apply_symm_apply]
    rw [he] at hm
    omega
  · intro h
    subst S
    have he : binarySupportEquiv.symm (∅ : Finset Omega)=(0 : BinaryWord) := by
      funext i
      simp [binarySupportEquiv]
    rw [he]
    exact golay.zero_mem

/-- Actual marked cocode coordinates on any fewer-than-eight-set are linearly independent. -/
theorem coordinateCocode_small_independent (S : Finset Omega) (hS : S.card<8) :
    LinearIndependent Bit (fun i : S => coordinateCocode i.val) := by
  classical
  apply Fintype.linearIndependent_iff.mpr
  intro a ha i
  let T : Finset S := Finset.univ.filter (fun j => a j≠0)
  let U : Finset Omega := T.image Subtype.val
  have hUS : U ⊆ S := by
    intro j hj
    obtain ⟨k,hk,rfl⟩ := Finset.mem_image.mp hj
    exact k.prop
  have hsum : (∑ j ∈ U,coordinateCocode j)=0 := by
    rw [Finset.sum_image (fun x _ y _ h => Subtype.ext h)]
    calc
      (∑ j ∈ T,coordinateCocode j.val) = ∑ j : S,a j • coordinateCocode j.val := by
        simp only [T,Finset.sum_filter]
        apply Finset.sum_congr rfl
        intro j _
        rcases bit_cases (a j) with h | h <;> simp [h]
      _ = 0 := ha
  have hu : U=∅ := (coordinateCocode_small_sum_eq_zero U
    (lt_of_le_of_lt (Finset.card_le_card hUS) hS)).mp hsum
  by_contra hi
  have hm : i.val ∈ U := Finset.mem_image.mpr ⟨i,by simp [T,hi],rfl⟩
  rw [hu] at hm
  exact Finset.notMem_empty _ hm

/-- The subspace generated by the actual coordinate cocode classes on S. -/
def coordinateCocodeSpan (S : Finset Omega) : Submodule Bit Cocode :=
  Submodule.span Bit (coordinateCocode '' (S : Set Omega))

end Atlas.Fischer
