import Atlas.LinearGroups.Symplectic.TransvectionImage
import Atlas.LinearAlgebra.SymplecticBasis
import Atlas.LinearGroups.Symplectic.Isometry

noncomputable section
namespace Atlas.Symplectic
variable {n : ℕ} {F : Type*} [Field F]

/-- Subgroup generated by all genuine symplectic transvections. -/
def transvectionGroup (n : ℕ) (F : Type*) [Field F] : Subgroup (Sp n F) :=
  Subgroup.closure {g | ∃ (v : Vector n F) (a : F), g = transvection v a}

theorem transvection_mem (v : Vector n F) (a : F) : transvection v a ∈ transvectionGroup n F :=
  Subgroup.subset_closure ⟨v,a,rfl⟩

/-- Two nonzero linear functionals do not cover a vector space by their kernels,
also over the field with two elements. -/
theorem exists_pairing_both {x y : Vector n F} (hx : x ≠ 0) (hy : y ≠ 0) :
    ∃ z, form x z ≠ 0 ∧ form y z ≠ 0 := by
  obtain ⟨u,hu⟩ := Atlas.AlternatingForm.exists_partner form form_nondegenerate hx
  obtain ⟨v,hv⟩ := Atlas.AlternatingForm.exists_partner form form_nondegenerate hy
  by_cases hyu : form y u = 0
  · by_cases hxv : form x v = 0
    · refine ⟨u+v,?_,?_⟩ <;> simp [map_add,hu,hv,hyu,hxv]
    · exact ⟨v,hxv,by rw [hv]; exact one_ne_zero⟩
  · exact ⟨u,by rw [hu]; exact one_ne_zero,hyu⟩

/-- The generated subgroup is transitive on nonzero vectors in every characteristic. -/
theorem exists_generated_send {x y : Vector n F} (hx : x ≠ 0) (hy : y ≠ 0) :
    ∃ g ∈ transvectionGroup n F, g • x = y := by
  obtain ⟨z,hxz,hyz⟩ := exists_pairing_both hx hy
  have hzy : form z y ≠ 0 := by rw [form_swap,neg_ne_zero]; exact hyz
  refine ⟨transvection (y-z) (form z y)⁻¹ * transvection (z-x) (form x z)⁻¹,
    (transvectionGroup n F).mul_mem (transvection_mem _ _) (transvection_mem _ _),?_⟩
  rw [mul_smul,transvection_send hxz,transvection_send hzy]

theorem transvection_fixes_of_orthogonal {e v : Vector n F} (hev : form e v = 0) (a : F) :
    transvection v a • e = e := by simp [transvection_apply,hev]

/-- Adjust the second vector of a hyperbolic pair while fixing the first. -/
theorem exists_generated_send_fix {e f u : Vector n F}
    (hef : form e f = 1) (heu : form e u = 1) :
    ∃ g ∈ transvectionGroup n F, g • e = e ∧ g • u = f := by
  have hue : form u e = -1 := by rw [form_swap,heu]
  by_cases huf : form u f = 0
  · let z := f+e
    have huz : form u z ≠ 0 := by simp [z,map_add,huf,hue]
    have hzf : form z f ≠ 0 := by simp [z,map_add,hef]
    have hezu : form e (z-u) = 0 := by simp [z,map_sub,map_add,hef,heu]
    have hefz : form e (f-z) = 0 := by simp [z,map_sub,map_add,hef]
    refine ⟨transvection (f-z) (form z f)⁻¹ * transvection (z-u) (form u z)⁻¹,
      (transvectionGroup n F).mul_mem (transvection_mem _ _) (transvection_mem _ _),?_,?_⟩
    · rw [mul_smul,transvection_fixes_of_orthogonal hezu,
        transvection_fixes_of_orthogonal hefz]
    · rw [mul_smul,transvection_send huz,transvection_send hzf]
  · refine ⟨transvection (f-u) (form u f)⁻¹,transvection_mem _ _,?_,transvection_send huf⟩
    apply transvection_fixes_of_orthogonal
    simp [map_sub,hef,heu]

end Atlas.Symplectic
