import Atlas.Fischer.FischerAssociatedOrders
import Atlas.Fischer.FischerFrameOrder
import Atlas.Fischer.PositiveRayAction
import Atlas.Fischer.RootSolvableNormal
import Atlas.Fischer.BasicFramePointwiseKernel
import Atlas.Fischer.CommutingPentadFrameTransitivity

noncomputable section
namespace Atlas.Sporadic.Fischer24
open Atlas.Fischer
attribute [local instance] scalarAlgebraRepresentation_range_normal

/-- The actual algebra-derived group generated by the reflecting-ray involutions. -/
abbrev Model := rootGeneratedRayGroup
abbrev PositiveModel := rootGeneratedRayParity.ker
abbrev AlgebraGroup := SemilinearAlgebraAutomorphism
abbrev LinearCover := rootGeneratedAlgebraParity.ker
abbrev Points := DisplayedReflectingRay
abbrev Frames := FischerFrame
abbrev DistinguishedClass := DistinguishedRootClass

def positiveInclusion : PositiveModel →* Model := rootGeneratedRayParity.ker.subtype
def projection : AlgebraGroup →* Model := fullSemilinearRayProjection
def positiveProjection : LinearCover →* PositiveModel := rootGeneratedPositiveProjection
def scalarComparison : AlgebraGroup ⧸ scalarAlgebraRepresentation.range ≃* Model :=
  fullSemilinearScalarQuotientEquiv

theorem finite : Finite Model := inferInstance
theorem card : Nat.card Model = 2510411418381323442585600 := rootGeneratedRayGroup_order_value
theorem order : Nat.card Model = 2^22*3^16*5^2*7^3*11*13*17*23*29 :=
  rootGeneratedRayGroup_order_factored
theorem positive_card : Nat.card PositiveModel = 1255205709190661721292800 :=
  rootGeneratedRayPositive_order
theorem algebra_card : Nat.card AlgebraGroup = 7531234255143970327756800 :=
  fullSemilinearAlgebra_order
theorem linear_card : Nat.card LinearCover = 3765617127571985163878400 :=
  rootGeneratedAlgebraPositive_order
theorem points_card : Nat.card Points = 306936 := displayedReflectingRay_card
theorem frames_card : Nat.card Frames = 2503413946215 := fischerFrame_count
theorem center : Subgroup.center Model = ⊥ := rootGeneratedRayGroup_center
theorem faithful : FaithfulSMul Model Points := inferInstance
theorem transitive : MulAction.IsPretransitive Model Points :=
  MulAction.IsPretransitive.mk rootGeneratedRayGroup_transitive
theorem pointwise_frame_kernel :
    basicFramePointwiseRayStabilizer = generatedCocodeRayHom.range :=
  basicFramePointwiseRayStabilizer_eq_cocode
theorem pentad_frames (t : OrderedCommutingTuple 5) : Nat.card (CommutingPentadFrame t) = 3 :=
  commutingPentadFrame_card t
theorem pentad_frames_transitive (t : OrderedCommutingTuple 5) :
    MulAction.IsPretransitive (MulAction.stabilizer Model t) (CommutingPentadFrame t) :=
  commutingPentadFrame_transitive t
theorem pentad_stabilizer (t : OrderedCommutingTuple 5) :
    Nat.card (MulAction.stabilizer Model t) = 589824 :=
  orderedCommutingPentad_stabilizer_order t
theorem positive_perfect : Group.IsPerfect PositiveModel := rootGeneratedRayParity_kernel_perfect
theorem positive_index : rootGeneratedRayParity.ker.index = 2 := rootGeneratedRayParity_index
theorem derived : commutator Model = rootGeneratedRayParity.ker := rootGeneratedRay_commutator
theorem not_simple : ¬IsSimpleGroup Model := by
  intro h
  letI := h
  rcases IsSimpleGroup.eq_bot_or_eq_top_of_normal rootGeneratedRayParity.ker inferInstance
      with hk | hk
  · have hc := positive_card
    change Nat.card rootGeneratedRayParity.ker = 1255205709190661721292800 at hc
    rw [hk, Subgroup.card_bot] at hc
    norm_num at hc
  · have hi := positive_index
    rw [hk] at hi
    norm_num at hi
theorem positive_faithful : FaithfulSMul PositiveModel Points := rootGeneratedRayPositive_faithful
theorem positive_transitive : MulAction.IsPretransitive PositiveModel Points :=
  rootGeneratedRayPositive_transitive
theorem projection_surjective : Function.Surjective projection := fullSemilinearRayProjection_surjective
theorem scalar_kernel : projection.ker = scalarAlgebraRepresentation.range :=
  fullSemilinearRayProjection_kernel
theorem no_solvable_normal (N : Subgroup Model) [N.Normal] [Group.IsSolvable N] : N = ⊥ :=
  rootGeneratedRay_solvable_normal_eq_bot N

/-- The full nonsimple group order package. Later rank-three and simplicity
certificates concern separately stated actions and the positive subgroup. -/
structure OrderConstruction : Prop where
  finite : Finite Model
  card : Nat.card Model = 2510411418381323442585600
  order : Nat.card Model = 2^22*3^16*5^2*7^3*11*13*17*23*29
  points : Nat.card Points = 306936
  frames : Nat.card Frames = 2503413946215
  generated : Subgroup.closure (Set.range distinguishedRootElement) = ⊤
  scalar_quotient : Nonempty (AlgebraGroup ⧸ scalarAlgebraRepresentation.range ≃* Model)
  positive_card : Nat.card PositiveModel = 1255205709190661721292800
  positive_perfect : Group.IsPerfect PositiveModel
  positive_index : rootGeneratedRayParity.ker.index = 2
  positive_faithful : FaithfulSMul PositiveModel Points
  positive_transitive : MulAction.IsPretransitive PositiveModel Points
  no_solvable_normal : ∀ (N : Subgroup Model) [N.Normal] [Group.IsSolvable N], N = ⊥

theorem construction : OrderConstruction where
  finite := finite
  card := card
  order := order
  points := points_card
  frames := frames_card
  generated := distinguishedRootClass_generates
  scalar_quotient := ⟨scalarComparison⟩
  positive_card := positive_card
  positive_perfect := positive_perfect
  positive_index := positive_index
  positive_faithful := positive_faithful
  positive_transitive := positive_transitive
  no_solvable_normal := no_solvable_normal

theorem exists_model : ∃ (G : Type) (_ : Group G), Finite G ∧
    Nat.card G = 2510411418381323442585600 :=
  ⟨Model, inferInstance, finite, card⟩

end Atlas.Sporadic.Fischer24
