import Atlas.LinearGroups.Orthogonal.DicksonInvariant
import Atlas.LinearGroups.Orthogonal.ReflectionConjugation
import Atlas.LinearAlgebra.QuadraticDicksonMultiplicative

/-! # The intrinsic even-reflection subgroup

The subgroup generated by pairs of anisotropic reflections is normal in the full
orthogonal group, in every characteristic. It is exactly the zero residual-parity
part of the reflection subgroup. No full reflection-generation assertion is used.
-/
noncomputable section
namespace Atlas.Orthogonal
open Atlas.Quadratic
variable {F V : Type*} [Field F] [AddCommGroup V] [Module F V]
variable (Q : QuadraticForm F V)

def evenReflectionSubgroup : Subgroup (isometrySubgroup Q) :=
  Subgroup.closure {g | ∃ a b ha hb, g = reflectionElement Q a ha * reflectionElement Q b hb}

theorem reflection_pair_mem_even (a b : V) (ha : Q a ≠ 0) (hb : Q b ≠ 0) :
    reflectionElement Q a ha * reflectionElement Q b hb ∈ evenReflectionSubgroup Q :=
  Subgroup.subset_closure ⟨a,b,ha,hb,rfl⟩

theorem evenReflection_le_reflection : evenReflectionSubgroup Q ≤ reflectionSubgroup Q := by
  apply (Subgroup.closure_le _).mpr
  rintro g ⟨a,b,ha,hb,rfl⟩
  exact (reflectionSubgroup Q).mul_mem (reflectionElement_mem _ _ _) (reflectionElement_mem _ _ _)

instance evenReflectionSubgroup_normal : (evenReflectionSubgroup Q).Normal := by
  constructor
  intro x hx g
  induction hx using Subgroup.closure_induction with
  | mem x hx =>
    obtain ⟨a,b,ha,hb,rfl⟩ := hx
    have he : g * (reflectionElement Q a ha * reflectionElement Q b hb) * g⁻¹ =
        (g * reflectionElement Q a ha * g⁻¹) * (g * reflectionElement Q b hb * g⁻¹) := by group
    rw [he, reflectionElement_conj, reflectionElement_conj]
    exact reflection_pair_mem_even _ _ _ _ _
  | one => simpa using (evenReflectionSubgroup Q).one_mem
  | mul x y hx hy ihx ihy =>
    have he : g * (x*y) * g⁻¹ = (g*x*g⁻¹) * (g*y*g⁻¹) := by group
    rw [he]
    exact (evenReflectionSubgroup Q).mul_mem ihx ihy
  | inv x hx ih =>
    have he : g*x⁻¹*g⁻¹ = (g*x*g⁻¹)⁻¹ := by group
    rw [he]
    exact (evenReflectionSubgroup Q).inv_mem ih

variable [FiniteDimensional F V] (hQ : Q.polarBilin.Nondegenerate)

include hQ in
private theorem value_mul_reflections (g h : isometrySubgroup Q)
    (hg : g ∈ reflectionSubgroup Q) :
    dicksonValue Q (g*h) = dicksonValue Q g + dicksonValue Q h :=
  dicksonParity_mul_of_mem_reflectionSubgroup Q hQ g hg h

include hQ in
private theorem value_reflection (a : V) (ha : Q a ≠ 0) :
    dicksonValue Q (reflectionElement Q a ha) = 1 := by
  have h := dicksonParity_reflection Q (isometryCarrierEquiv Q 1) hQ a ha
  have he : reflectedIsometry Q (isometryCarrierEquiv Q 1) a ha =
      isometryCarrierEquiv Q (reflectionElement Q a ha) := by
    apply DFunLike.ext
    intro x
    rfl
  rw [he] at h
  change dicksonValue Q (reflectionElement Q a ha) = dicksonValue Q 1 + 1 at h
  simpa using h

include hQ in
theorem evenReflection_dickson_zero (g : isometrySubgroup Q)
    (hg : g ∈ evenReflectionSubgroup Q) : dicksonValue Q g = 0 := by
  induction hg using Subgroup.closure_induction with
  | mem g hg =>
    obtain ⟨a,b,ha,hb,rfl⟩ := hg
    rw [value_mul_reflections Q hQ _ _ (reflectionElement_mem _ _ _),
      value_reflection Q hQ, value_reflection Q hQ]
    decide
  | one => exact dicksonValue_one Q
  | mul x y hx hy ihx ihy =>
    rw [value_mul_reflections Q hQ _ _ (evenReflection_le_reflection Q hx), ihx, ihy, add_zero]
  | inv x hx ih => simpa using ih

include hQ in
private theorem reflection_zero_mem_even_with_base (a : V) (ha : Q a ≠ 0)
    (g : isometrySubgroup Q) (hg : g ∈ reflectionSubgroup Q)
    (hz : dicksonValue Q g = 0) : g ∈ evenReflectionSubgroup Q := by
  let π := QuotientGroup.mk' (evenReflectionSubgroup Q)
  let t := π (reflectionElement Q a ha)
  have ht : t*t = 1 := by
    change π (reflectionElement Q a ha) * π (reflectionElement Q a ha) = 1
    rw [← map_mul, ← pow_two, reflectionElement_square, map_one]
  have hti : t⁻¹ = t := inv_eq_of_mul_eq_one_right ht
  have hall : ∀ k, k ∈ reflectionSubgroup Q →
      (dicksonValue Q k = 0 ∧ π k = 1) ∨ (dicksonValue Q k = 1 ∧ π k = t) := by
    intro k hk
    induction hk using Subgroup.closure_induction with
    | mem k hk =>
      obtain ⟨b,hb,rfl⟩ := hk
      right
      refine ⟨value_reflection Q hQ _ _, ?_⟩
      have hp : π (reflectionElement Q b hb * reflectionElement Q a ha) = 1 :=
        (QuotientGroup.eq_one_iff _).mpr (reflection_pair_mem_even Q b a hb ha)
      rw [map_mul] at hp
      change π (reflectionElement Q b hb) * t = 1 at hp
      have he := congrArg (fun z => z*t) hp
      simpa only [mul_assoc, ht, mul_one, one_mul] using he
    | one => exact Or.inl ⟨dicksonValue_one Q, map_one π⟩
    | mul x y hx hy ihx ihy =>
      rw [value_mul_reflections Q hQ x y hx, map_mul]
      rcases ihx with ⟨hx0,hxp⟩ | ⟨hx1,hxp⟩ <;>
        rcases ihy with ⟨hy0,hyp⟩ | ⟨hy1,hyp⟩
      · exact Or.inl ⟨by rw [hx0,hy0,add_zero], by rw [hxp,hyp,mul_one]⟩
      · exact Or.inr ⟨by rw [hx0,hy1,zero_add], by rw [hxp,hyp,one_mul]⟩
      · exact Or.inr ⟨by rw [hx1,hy0,add_zero], by rw [hxp,hyp,mul_one]⟩
      · exact Or.inl ⟨by rw [hx1,hy1]; decide, by rw [hxp,hyp,ht]⟩
    | inv x hx ih =>
      rw [dicksonValue_inv, map_inv]
      rcases ih with ⟨hz,hp⟩ | ⟨ho,hp⟩
      · exact Or.inl ⟨hz, by rw [hp,inv_one]⟩
      · exact Or.inr ⟨ho, by rw [hp,hti]⟩
  rcases hall g hg with ⟨_,hp⟩ | ⟨ho,_⟩
  · exact (QuotientGroup.eq_one_iff _).mp hp
  · rw [hz] at ho
    exact False.elim (zero_ne_one ho)

include hQ in
/-- Exact kernel identification inside the actual reflection subgroup. -/
theorem mem_evenReflection_iff (g : isometrySubgroup Q) :
    g ∈ evenReflectionSubgroup Q ↔ g ∈ reflectionSubgroup Q ∧ dicksonValue Q g = 0 := by
  constructor
  · intro hg
    exact ⟨evenReflection_le_reflection Q hg, evenReflection_dickson_zero Q hQ g hg⟩
  · rintro ⟨hg,hz⟩
    by_cases hex : ∃ a, Q a ≠ 0
    · obtain ⟨a,ha⟩ := hex
      exact reflection_zero_mem_even_with_base Q hQ a ha g hg hz
    · have hbot : reflectionSubgroup Q = ⊥ := by
        apply le_antisymm _ bot_le
        apply (Subgroup.closure_le _).mpr
        rintro k ⟨a,ha,rfl⟩
        exact False.elim (hex ⟨a,ha⟩)
      rw [hbot, Subgroup.mem_bot] at hg
      rw [hg]
      exact (evenReflectionSubgroup Q).one_mem

include hQ in
/-- The residual-parity character kernel, embedded in the full isometry group,
is precisely the normal subgroup generated by pairs of reflections. -/
theorem reflectionDicksonCharacter_kernel_image :
    (reflectionDicksonCharacter Q hQ).ker.map (reflectionSubgroup Q).subtype =
      evenReflectionSubgroup Q := by
  ext g
  rw [mem_evenReflection_iff Q hQ]
  constructor
  · rintro ⟨k,hk,rfl⟩
    exact ⟨k.prop, hk⟩
  · rintro ⟨hg,hz⟩
    exact ⟨⟨g,hg⟩, hz, rfl⟩

include hQ in
/-- An anisotropic vector witnesses that the reflection parity character has both values. -/
theorem reflectionDicksonCharacter_surjective (a : V) (ha : Q a ≠ 0) :
    Function.Surjective (reflectionDicksonCharacter Q hQ) := by
  intro x
  have hx : x.toAdd = 0 ∨ x.toAdd = 1 := by
    have h := ZMod.val_lt x.toAdd
    have he := ZMod.natCast_zmod_val x.toAdd
    interval_cases hval : x.toAdd.val <;> simp_all
  rcases hx with hx | hx
  · refine ⟨1, ?_⟩
    apply Multiplicative.toAdd.injective
    rw [map_one]
    exact hx.symm
  · refine ⟨⟨reflectionElement Q a ha, reflectionElement_mem Q a ha⟩, ?_⟩
    apply Multiplicative.toAdd.injective
    change dicksonValue Q (reflectionElement Q a ha) = x.toAdd
    rw [value_reflection Q hQ, hx]

/-- The exact two-element quotient of the reflection subgroup by its parity kernel. -/
def reflectionParityQuotientEquiv (a : V) (ha : Q a ≠ 0) :
    reflectionSubgroup Q ⧸ (reflectionDicksonCharacter Q hQ).ker ≃*
      Multiplicative (ZMod 2) :=
  QuotientGroup.quotientKerEquivOfSurjective (reflectionDicksonCharacter Q hQ)
    (reflectionDicksonCharacter_surjective Q hQ a ha)

include hQ in
/-- Exact index two inside the actual reflection subgroup, without identifying it with full O. -/
theorem card_evenReflection_mul_two (a : V) (ha : Q a ≠ 0) :
    Nat.card (evenReflectionSubgroup Q) * 2 = Nat.card (reflectionSubgroup Q) := by
  have h := Subgroup.card_eq_card_quotient_mul_card_subgroup
    (reflectionDicksonCharacter Q hQ).ker
  have he := Nat.card_congr (reflectionParityQuotientEquiv Q hQ a ha).toEquiv
  have hk := Nat.card_congr ((reflectionDicksonCharacter Q hQ).ker.equivMapOfInjective
    (reflectionSubgroup Q).subtype Subtype.val_injective).toEquiv
  rw [reflectionDicksonCharacter_kernel_image] at hk
  have htwo : Nat.card (Multiplicative (ZMod 2)) = 2 := by
    change Nat.card (ZMod 2) = 2
    simp
  rw [he, htwo, hk] at h
  exact (mul_comm _ _).trans h.symm

end Atlas.Orthogonal
