import Atlas.LinearGroups.Orthogonal.Elementary
import Atlas.LinearGroups.Orthogonal.EvenComparison
import Atlas.LinearGroups.Symplectic.Generation

/-! # Actual Siegel generation of the full B group in characteristic two -/
noncomputable section
namespace Atlas.Orthogonal
variable {n : ℕ} {F : Type*} [Field F] [CharP F 2] [PerfectRing F 2]

def evenSingularLift (u : VectorD n F) : VectorB n F :=
  (u, (frobeniusEquiv F 2).symm (formD n F u))

theorem evenSingularLift_singular (u : VectorD n F) : formB n F (evenSingularLift u) = 0 := by
  rw [formB_apply]
  change formD n F u + ((frobeniusEquiv F 2).symm (formD n F u))^2 = 0
  have h : ((frobeniusEquiv F 2).symm (formD n F u))^2 = formD n F u :=
    (frobeniusEquiv F 2).apply_symm_apply _
  rw [h, CharTwo.add_self_eq_zero]

theorem polarB_scalar_z (u : VectorB n F) (a : F) :
    (formB n F).polarBilin u (a • z) = 0 := by
  simp only [map_smul, polarB_apply, z, map_zero, CharTwo.two_eq_zero, zero_mul, add_zero, smul_zero]

theorem even_siegel_transvection (u : VectorD n F) (a : F) :
    evenProjection (siegelElement (formB n F) (evenSingularLift u) (a • z)
      (evenSingularLift_singular u) (polarB_scalar_z _ a)) = Atlas.Symplectic.transvection u (a^2) := by
  apply Atlas.Symplectic.ext_action
  intro x
  rw [evenProjection_apply, Atlas.Symplectic.transvection_apply]
  change (Atlas.Quadratic.siegel (formB n F) (evenSingularLift u) (a • z) (x, 0)).1 = _
  have hq : formB n F (a • z (n := n)) = a^2 := by
    rw [(formB n F).map_smul, formB_z]
    simp only [smul_eq_mul, mul_one, pow_two]
  have hp : (formB n F).polarBilin (x, 0) (evenSingularLift u) = Atlas.Symplectic.form x u := by
    simp only [polarB_apply, CharTwo.two_eq_zero, zero_mul, add_zero, evenSingularLift,
      polarD_eq_symplectic]
  simp only [Atlas.Quadratic.siegel, polarB_scalar_z, zero_smul, add_zero, hq, hp]
  change x - (Atlas.Symplectic.form x u • (a • z (n := n))).1 -
    ((a^2 * Atlas.Symplectic.form x u) • evenSingularLift u).1 = _
  simp only [z, evenSingularLift, Prod.smul_fst, smul_zero, sub_zero]
  funext i
  simp only [Pi.sub_apply, Pi.add_apply, Pi.smul_apply, smul_eq_mul, CharTwo.sub_eq_add]

theorem even_transvection_mem_image (u : VectorD n F) (a : F) :
    Atlas.Symplectic.transvection u a ∈ (elementarySubgroup (formB n F)).map evenProjection := by
  let c := (frobeniusEquiv F 2).symm a
  have hc : c^2 = a := (frobeniusEquiv F 2).apply_symm_apply a
  refine ⟨siegelElement (formB n F) (evenSingularLift u) (c • z)
    (evenSingularLift_singular u) (polarB_scalar_z _ c), siegelElement_mem _ _ _ _ _, ?_⟩
  rw [even_siegel_transvection, hc]

/-- All full B isometries in characteristic two are generated by actual Siegel isometries. -/
theorem even_elementary_eq_top : elementarySubgroup (formB n F) = ⊤ := by
  have him : (elementarySubgroup (formB n F)).map evenProjection = ⊤ := by
    apply top_unique
    rw [← Atlas.Symplectic.transvectionGroup_eq_top]
    change Subgroup.closure _ ≤ _
    rw [Subgroup.closure_le]
    rintro g ⟨u, a, rfl⟩
    exact even_transvection_mem_image u a
  apply top_unique
  intro g _
  have hg : evenProjection g ∈ (elementarySubgroup (formB n F)).map evenProjection := by rw [him]; trivial
  obtain ⟨h, hh, he⟩ := hg
  exact evenProjection_injective he ▸ hh

end Atlas.Orthogonal
