import Atlas.LinearGroups.Orthogonal.RootSubgroupCoordinates
import Mathlib.LinearAlgebra.Basis.Basic

noncomputable section
namespace Atlas.Orthogonal
open Atlas.Quadratic Module
variable {F V : Type*} [Field F] [AddCommGroup V] [Module F V]

/-- A root subgroup is generated by its one-parameter subgroups along a complement basis. -/
theorem rootSubgroup_le_of_basis {ι : Type*} [Fintype ι]
    (Q : QuadraticForm F V) (u f : V) (hu : Q u=0) (huf : Q.polarBilin u f=1)
    (b : Basis ι F (complement Q u f)) (H : Subgroup (isometrySubgroup Q))
    (hb : ∀(i : ι) (c : F), rootComplementHom Q u f hu (Multiplicative.ofAdd (c • b i)) ∈ H) :
    rootSubgroup Q u hu ≤ H := by
  rw [←rootComplementHom_range Q u f hu huf]
  rintro g ⟨v,rfl⟩
  have hs (s : Finset ι) :
      rootComplementHom Q u f hu
        (Multiplicative.ofAdd (∑ i ∈ s, b.repr v.toAdd i • b i)) ∈ H := by
    classical
    induction s using Finset.induction_on with
    | empty => simpa using H.one_mem
    | @insert i s hi ih =>
      rw [Finset.sum_insert hi]
      change rootComplementHom Q u f hu
        (Multiplicative.ofAdd (b.repr v.toAdd i • b i) *
          Multiplicative.ofAdd (∑j∈s,b.repr v.toAdd j • b j)) ∈ H
      rw [map_mul]
      exact H.mul_mem (hb i _) ih
  simpa only [b.sum_repr v.toAdd,ofAdd_toAdd] using hs Finset.univ

end Atlas.Orthogonal

namespace Atlas.Orthogonal
open Atlas.Quadratic Module
variable {F V : Type*} [Field F] [AddCommGroup V] [Module F V]

/-- Only transformations with coordinate centers and one coordinate parameter occur in this generating set. -/
def coordinateRootSubgroup {ι : Type*} (Q : QuadraticForm F V) (b : Basis ι F V) :
    Subgroup (isometrySubgroup Q) :=
  Subgroup.closure {g | ∃ (i j : ι) (c : F) (hu : Q (b i)=0) (huv : Q.polarBilin (b i) (c • b j)=0),
    g=siegelElement Q (b i) (c • b j) hu huv}

theorem coordinateRoot_mem {ι : Type*} (Q : QuadraticForm F V) (b : Basis ι F V)
    (i j : ι) (c : F) (hu : Q (b i)=0) (huv : Q.polarBilin (b i) (c • b j)=0) :
    siegelElement Q (b i) (c • b j) hu huv ∈ coordinateRootSubgroup Q b :=
  Subgroup.subset_closure ⟨i,j,c,hu,huv,rfl⟩

theorem coordinateRootSubgroup_le_elementary {ι : Type*} (Q : QuadraticForm F V)
    (b : Basis ι F V) : coordinateRootSubgroup Q b ≤ elementarySubgroup Q := by
  apply (Subgroup.closure_le _).mpr
  rintro g ⟨i,j,c,hu,huv,rfl⟩
  exact Subgroup.subset_closure ⟨b i,c • b j,hu,huv,rfl⟩

/-- A coordinate complement basis supplies the entire root subgroup at its coordinate center. -/
theorem rootSubgroup_le_coordinateRootSubgroup {ι κ : Type*} [Fintype κ]
    (Q : QuadraticForm F V) (b : Basis ι F V) (i : ι) (f : V)
    (hu : Q (b i)=0) (huf : Q.polarBilin (b i) f=1)
    (w : Basis κ F (complement Q (b i) f)) (k : κ → ι)
    (hw : ∀j,(w j).val=b (k j)) :
    rootSubgroup Q (b i) hu ≤ coordinateRootSubgroup Q b := by
  apply rootSubgroup_le_of_basis Q (b i) f hu huf w
  intro j c
  have he : (c • w j).val=c • b (k j) := by rw [Submodule.coe_smul,hw]
  change siegelElement Q (b i) (c • w j).val hu _ ∈ coordinateRootSubgroup Q b
  simp only [he]
  exact coordinateRoot_mem Q b i (k j) c hu _

end Atlas.Orthogonal
