import Atlas.LinearGroups.Orthogonal.ElementaryReflectionGeneration
import Atlas.LinearGroups.Orthogonal.DicksonElementaryD

/-! # Full split-D reflection generation in stable rank, in every characteristic

The induction proves joint generation in every rank; only the final ambient
rank uses the inclusion of the actual elementary group in the reflection group.
Thus the exceptional four-dimensional reflection-generation case is not assumed.
-/
noncomputable section
namespace Atlas.Orthogonal
variable {F : Type*} [Field F]

/-- The actual full split-D orthogonal group is generated by anisotropic reflections
in rank at least three, including over fields of characteristic two. -/
theorem reflectionSubgroupD_eq_top_stable (n : ℕ) :
    reflectionSubgroup (formD (n + 3) F) = ⊤ := by
  have h := elementary_sup_reflectionsD_eq_top (F := F) (n + 3)
  change elementarySubgroup (formD (n + 3) F) ⊔
    reflectionSubgroup (formD (n + 3) F) = ⊤ at h
  rwa [sup_eq_right.mpr (elementaryD_le_reflections_stable n)] at h

end Atlas.Orthogonal
