import Atlas.Lattices.IcosianGeneratorLift
import Atlas.Lattices.IcosianComparisonSourceMembership
import Atlas.Lattices.IcosianEvenGenerators

set_option backward.isDefEq.respectTransparency false
noncomputable section
namespace Atlas.Lattices
open Atlas.Algebra Atlas.Codes
open scoped BigOperators

/-- The actual lattice is generated by the twenty-four doubled integral basis
vectors and twelve binary lifts of the six-dimensional matrix glue. -/
theorem icosianLeechModule_le_of_generators (S : Submodule ℤ IcosianCoordinates)
    (hS : ∀ j : Fin 36,icosianComparisonSourceGenerator j∈S) :
    icosianLeechModule.restrictScalars ℤ ≤ S := by
  intro x hx
  let a : Fin 6 → GoldenFour := icosianGlueFreePart (fun i j =>
    goldenModuloTwo (icosianIntegralCoefficients (x i) j))
  let y := icosianGlueLift a
  have hyS : y∈S := icosianGlueLift_mem S (fun k => hS _) a
  have hyL : y∈icosianLeechModule :=
    icosianGlueLift_mem (icosianLeechModule.restrictScalars ℤ)
      (fun k => icosianComparisonSourceGenerator_mem _) a
  have hzL : x-y∈icosianLeechModule := icosianLeechModule.sub_mem hx hyL
  let c : Fin 3 → Fin 4 → GoldenFour := fun i j =>
    goldenModuloTwo (icosianIntegralCoefficients ((x-y) i) j)
  have hc : (fun i => icosianMatrixFromCoefficients (c i)) ∈
      icosianMatrixGlue GoldenFour :=
    (icosianLeechModule_matrix_glue (x-y)).mp hzL
  have hdiff (i : Fin 3) (j : Fin 4) : c i j=
      goldenModuloTwo (icosianIntegralCoefficients (x i) j)-
      goldenModuloTwo (icosianGlueLiftCoefficients a i j) := by
    have he : icosianIntegralCoefficients ((x-y) i)=
        icosianIntegralCoefficients (x i)-icosianIntegralCoefficients (y i) :=
      icosianIntegralEquiv.map_sub (x i) (y i)
    change goldenModuloTwo (icosianIntegralCoefficients ((x-y) i) j)=_
    rw [he]
    change goldenModuloTwo (icosianIntegralCoefficients (x i) j-
      icosianIntegralCoefficients (icosianGlueLift a i) j)=_
    rw [icosianGlueLift_integralCoefficients,map_sub]
  have hfree : icosianGlueFreePart c=0 := by
    have hl := icosianGlueLift_free a
    have hs (i : Fin 3) (j : Fin 4)
        (hk : goldenModuloTwo (icosianGlueLiftCoefficients a i j)=
          goldenModuloTwo (icosianIntegralCoefficients (x i) j)) : c i j=0 := by
      rw [hdiff,hk,sub_self]
    funext k
    fin_cases k
    · exact hs 1 1 (congrFun hl 0)
    · exact hs 1 3 (congrFun hl 1)
    · exact hs 2 0 (congrFun hl 2)
    · exact hs 2 1 (congrFun hl 3)
    · exact hs 2 2 (congrFun hl 4)
    · exact hs 2 3 (congrFun hl 5)
  have hc0 : c=0 := by
    apply icosianGlue_free_zero c hc
    · exact congrFun hfree 0
    · exact congrFun hfree 1
    · funext j
      fin_cases j
      · exact congrFun hfree 2
      · exact congrFun hfree 3
      · exact congrFun hfree 4
      · exact congrFun hfree 5
  have hzS : x-y∈S := icosianEven_mem_of_generators S
    (fun n => hS _) (x-y) (fun i j => congrFun (congrFun hc0 i) j)
  have := S.add_mem hzS hyS
  simpa only [sub_add_cancel] using this

end Atlas.Lattices
