import Atlas.Conway.IcosianReflectionCovariance
import Atlas.Conway.IcosianRootPointCount

set_option backward.isDefEq.respectTransparency false
noncomputable section
namespace Atlas.Conway
open Atlas.Algebra Atlas.Lattices

def icosianRootReflectionOf (r : IcosianRoot) : icosianHermitianGroup :=
  icosianRootReflection (icosianCoordinateEmbedding r.val) r.property.2
    ⟨r.val,r.property.1,rfl⟩

theorem icosianRootReflectionOf_apply (r : IcosianRoot) (v : IcosianRationalCoordinates) :
    (icosianRootReflectionOf r).val v=icosianReflection (icosianCoordinateEmbedding r.val) v := rfl

theorem icosianRootReflectionOf_rightUnit (r : IcosianRoot) (u : icosianNormOneGroup) :
    icosianRootReflectionOf (icosianRootRightUnit r u)=icosianRootReflectionOf r := by
  apply Subtype.ext
  apply LinearEquiv.ext
  intro v
  exact icosianReflection_unit_multiple (icosianCoordinateEmbedding r.val) v u

theorem icosianRootReflectionOf_eq_of_point_eq (r s : IcosianRoot)
    (h : icosianRootPoint r=icosianRootPoint s) :
    icosianRootReflectionOf r=icosianRootReflectionOf s := by
  obtain ⟨u,rfl⟩ := (icosianRootPoint_eq_iff s r).mp h
  exact icosianRootReflectionOf_rightUnit s u

/-- Reflection in an actual root line; generator independence is proved below. -/
def icosianLineReflection (p : IcosianRootPoint) : icosianHermitianGroup :=
  icosianRootReflectionOf p.property.choose

theorem icosianLineReflection_root (r : IcosianRoot) :
    icosianLineReflection (icosianRootToPoint r)=icosianRootReflectionOf r :=
  icosianRootReflectionOf_eq_of_point_eq _ _ (icosianRootToPoint r).property.choose_spec

theorem icosianLineReflection_square (p : IcosianRootPoint) :
    icosianLineReflection p*icosianLineReflection p=1 :=
  icosianRootReflection_square _ p.property.choose.property.2
    ⟨p.property.choose.val,p.property.choose.property.1,rfl⟩

/-- The subgroup generated by all actual quaternionic root reflections. -/
def icosianReflectionGroup : Subgroup icosianHermitianGroup :=
  Subgroup.closure (Set.range icosianLineReflection)

theorem icosianLineReflection_mem (p : IcosianRootPoint) :
    icosianLineReflection p∈icosianReflectionGroup :=
  Subgroup.subset_closure ⟨p,rfl⟩

theorem icosianRootReflectionOf_mem (r : IcosianRoot) :
    icosianRootReflectionOf r∈icosianReflectionGroup := by
  rw [← icosianLineReflection_root r]
  exact icosianLineReflection_mem _

end Atlas.Conway
