import Atlas.Conway.ShortenedGolayOctadSpan
import Atlas.Conway.MonomialOctadCommutators
import Atlas.Mathieu.OctadExteriorTransitivity

noncomputable section
namespace Atlas.Conway
open Atlas.Codes Atlas.Lattices
attribute [local instance] Classical.propDecidable
set_option maxRecDepth 10000

/-- Differences under actual Mathieu permutations fixing both marked coordinates. -/
def markedShortDifferences : Set golay := {d | ∃ g : Mathieu24CodeModel,
  g.val ((0,0),0) = ((0,0),0) ∧ g.val ((0,0),1) = ((0,0),1) ∧
  ∃ c : golay, c.val ((0,0),0) = 0 ∧ c.val ((0,0),1) = 0 ∧
    d = golayPermutationEquiv g c - c}

def markedShortDifferenceSpan : Submodule Bit golay := Submodule.span Bit markedShortDifferences

def shortSeedP : Finset Omega := tetrad (0,1) ∪ tetrad (1,0)
def shortSeedQ : Finset Omega := tetrad (0,1) ∪ tetrad (1,1)
def shortSeedO : Finset Omega := tetrad (1,0) ∪ tetrad (1,1)

theorem shortSeedP_mem : shortSeedP ∈ octads := tetrad_pair_octad _ _ (by decide)
theorem shortSeedQ_mem : shortSeedQ ∈ octads := tetrad_pair_octad _ _ (by decide)
theorem shortSeedO_mem : shortSeedO ∈ octads := tetrad_pair_octad _ _ (by decide)

theorem shortSeed_difference : octadCode shortSeedQ shortSeedQ_mem -
    octadCode shortSeedP shortSeedP_mem = octadCode shortSeedO shortSeedO_mem := by
  apply Subtype.ext
  decide +kernel

theorem shortSeed_mem_differenceSpan : octadCode shortSeedO shortSeedO_mem ∈ markedShortDifferenceSpan := by
  obtain ⟨g,hi,hj,hg⟩ := mathieu24_pair_fixing_octad_avoiding_transitive
    shortSeedP shortSeedQ shortSeedP_mem shortSeedQ_mem ((0,0),0) ((0,0),1)
    (by decide) (by decide) (by decide) (by decide) (by decide)
  apply Submodule.subset_span
  refine ⟨g,hi,hj,octadCode shortSeedP shortSeedP_mem,by decide,by decide,?_⟩
  rw [permutation_octadCode _ _ _ shortSeedP_mem shortSeedQ_mem hg,shortSeed_difference]

theorem shortened_octad_mem_differenceSpan (c : golay) (hc : c ∈ markedShortOctads) :
    c ∈ markedShortDifferenceSpan := by
  have hO : support c.val ∈ octads := (octads_mem _).mpr ⟨c,hc.2.2,rfl⟩
  have hi : ((0,0),0) ∉ support c.val := by simpa [support] using hc.1
  have hj : ((0,0),1) ∉ support c.val := by simpa [support] using hc.2.1
  obtain ⟨g,hgi,hgj,hg⟩ := mathieu24_pair_fixing_octad_avoiding_transitive
    shortSeedO (support c.val) shortSeedO_mem hO ((0,0),0) ((0,0),1)
    (by decide) (by decide) (by decide) hi hj
  have he : octadCode (support c.val) hO = c := Subtype.ext (binarySupportEquiv.left_inv c.val)
  have hd : golayPermutationEquiv g (octadCode shortSeedO shortSeedO_mem) -
      octadCode shortSeedO shortSeedO_mem ∈ markedShortDifferenceSpan :=
    Submodule.subset_span ⟨g,hgi,hgj,octadCode shortSeedO shortSeedO_mem,by decide,by decide,rfl⟩
  rw [permutation_octadCode _ _ _ shortSeedO_mem hO hg,he] at hd
  simpa only [sub_add_cancel] using markedShortDifferenceSpan.add_mem hd shortSeed_mem_differenceSpan

/-- The concrete shortened Golay module is generated by Mathieu differences. -/
theorem marked_short_differences_span : markedShortDifferenceSpan =
    (golayTwoCoordinateProjection ((0,0),0) ((0,0),1)).ker := by
  apply le_antisymm
  · apply Submodule.span_le.mpr
    rintro d ⟨g,hi,hj,c,hci,hcj,rfl⟩
    have hi' : g.val.symm ((0,0),0) = ((0,0),0) := (Equiv.symm_apply_eq g.val).mpr hi.symm
    have hj' : g.val.symm ((0,0),1) = ((0,0),1) := (Equiv.symm_apply_eq g.val).mpr hj.symm
    change (c.val (g.val.symm ((0,0),0)) - c.val ((0,0),0),
      c.val (g.val.symm ((0,0),1)) - c.val ((0,0),1)) = (0,0)
    rw [hi',hj',sub_self,sub_self]
  · rw [← marked_short_octads_span]
    exact Submodule.span_le.mpr shortened_octad_mem_differenceSpan

end Atlas.Conway
