import Mathlib.GroupTheory.SpecificGroups.Cyclic.Basic
import Mathlib.Data.Fin.VecNotation
import Mathlib.Tactic

/-! # A group generated by two commuting involutions has at most four elements -/
namespace Atlas
variable {G : Type*} [Group G]

theorem card_le_four_of_two_commuting_involutions (a b : G) (ha : a*a = 1) (hb : b*b = 1)
    (hab : a*b = b*a) (hgen : Subgroup.closure ({a,b} : Set G) = ⊤) : Nat.card G ≤ 4 := by
  have hab_a : (a*b)*a = b := by rw [mul_assoc, ← hab, ← mul_assoc, ha, one_mul]
  have hab_b : (a*b)*b = a := by rw [mul_assoc, hb, mul_one]
  have ha_ab : a*(a*b) = b := by rw [← mul_assoc, ha, one_mul]
  have hb_ab : b*(a*b) = a := by rw [← mul_assoc, ← hab, hab_b]
  have hab_ab : (a*b)*(a*b) = 1 := by rw [← mul_assoc, hab_a, hb]
  have hai : a⁻¹ = a := inv_eq_of_mul_eq_one_right ha
  have hbi : b⁻¹ = b := inv_eq_of_mul_eq_one_right hb
  have habi : (a*b)⁻¹ = a*b := inv_eq_of_mul_eq_one_right hab_ab
  let S : Subgroup G :=
    { carrier := {x | x=1 ∨ x=a ∨ x=b ∨ x=a*b}
      one_mem' := Or.inl rfl
      mul_mem' := by
        rintro x y (rfl|rfl|rfl|rfl) (rfl|rfl|rfl|rfl) <;>
          simp only [one_mul, mul_one, ha, hb, hab_a, hab_b, ha_ab, hb_ab, hab_ab,
            ← hab, Set.mem_setOf_eq] <;> tauto
      inv_mem' := by
        rintro x (rfl|rfl|rfl|rfl) <;>
          simp only [inv_one, hai, hbi, habi, Set.mem_setOf_eq] <;> tauto }
  have hs : Subgroup.closure ({a,b} : Set G) ≤ S := by
    apply (Subgroup.closure_le _).mpr
    intro x hx
    rcases Set.mem_insert_iff.mp hx with rfl | hx
    · exact Or.inr (Or.inl rfl)
    · have hx' : x = b := Set.mem_singleton_iff.mp hx
      exact Or.inr (Or.inr (Or.inl hx'))
  rw [hgen] at hs
  let f : Fin 4 → G := ![1,a,b,a*b]
  have hf : Function.Surjective f := by
    intro x
    rcases hs (Subgroup.mem_top x) with h|h|h|h
    · exact ⟨0, h.symm⟩
    · exact ⟨1, h.symm⟩
    · exact ⟨2, h.symm⟩
    · exact ⟨3, h.symm⟩
  simpa using Nat.card_le_card_of_surjective f hf

end Atlas
